export default {
    text01: 'Connected with',
    text02: 'Show Portis',
    text03: 'Account',
    text04: 'Disconnect',
    text05: 'Change',
    text06: 'Copy Address',
    text07: 'View on HECO',
    text08: 'Recent Transactions',
    text09: 'clear all',
    text10: 'Your transactions will appear here...',
// pages/earn/index
    text11: 'TreeSwap liquidity mining',
    text12: 'Deposit your Liquidity Provider tokens to receive TTQ, the TreeSwap protocol governance token.',
    text13: 'Read more about TTQ',
    text14: 'Participating pools',
    text15: 'No active pools',
//pages/earn/manage
    text16: 'Liquidity Mining',
    text17: 'Total deposits',
    text18: 'Pool Rate: ',
    text19: 'Step 1. Get TTQ Liquidity tokens',
    text20: "TTQ LP tokens are required. Once you've added liquidity to the",
    text21: 'pool you can stake your liquidity tokens on this page.',
    text22: 'Add',
    text23: 'liquidity',
    text24: 'Your liquidity deposits',
    text25: 'Your unclaimed TTQ',
    text26: 'Claim',
    text27: ' When you withdraw, the contract will automagically claim TTQ on your behalf!',
    text28: 'Deposit',
    text29: 'Deposit TTQ LP Tokens',
    text30: 'Withdraw',
    text31: "TTQ LP tokens available",
//pages/migratev1/
    text32: 'Migrate Liquidity',
//components/positioncard/index
    text33: 'Your position',
    text34: 'Your pool share:',
    text35: "By adding liquidity youll earn 0.3% of all trades on this pair proportional to your share of the pool.Fees are added to the pool, accrue in real time and can be claimed by withdrawing your liquidity.",
    text36: 'Loading',
    text37: 'Manage',
    text38: 'Your total pool tokens:',
    text39: 'Pool tokens in rewards pool:',
    text40: 'Pooled',
    text41: 'View accrued fees and analytics',
    text42: 'Add',
    text43: 'Remove',
    text44: 'Manage Liquidity in Rewards Pool',
//swap/AdvancedSwapDetails
    text45: 'Minimum received',
    text46: 'Maximum sold',
    text47: 'Price Impact',
    text48: 'Liquidity Provider Fee',
//pages/removeliquidity/index
    text49: 'Removing pool tokens converts your position back into underlying tokens at the current rate, proportional to your share of the pool. Accrued fees are included in the amounts you receive.',
    text50: 'Amount',
    text51: 'Simple',
    text52: 'Detailed',
    // text53: 'Receive WHT',
    // text54: 'Receive HT',
    text55: 'Price',
    text56: 'Approving',
    text57: 'Approved',
    text58: 'Approve',
    text59: 'Connect Wallet',
    text60: 'You will receive',
    text61: 'Output is estimated. If the price changes by more than ',
    text62: '% your transaction will revert.',
    text63: 'Confirm',
    text64: 'Please try to refresh the page and reconnect the wallet',
    text65: 'Back',
    text66: 'New to Heco?',
    text67: 'Learn more about wallets',
    text68: 'Connect to a wallet',
    text69: 'Swap Anyway',
    text70: 'Confirm Swap',
}