export default {
    text01: 'Connected with',
    text02: 'Show Portis',
    text03: 'Account',
    text04: 'Disconnect',
    text05: 'Change',
    text06: 'Copy Address',
    text07: 'View on HECO',
    text08: 'Recent Transactions',
    text09: 'clear all',
    text10: 'Your transactions will appear here...',
// pages/earn/index
    text11: 'Uniswap liquidity mining',
    text12: 'Deposit your Liquidity Provider tokens to receive UNI, the Uniswap protocol governance token.',
    text13: 'Read more about UNI',
    text14: 'Participating pools',
    text15: 'No active pools',
//pages/earn/manage
    text16: 'Liquidity Mining',
    text17: 'Total deposits',
    text18: 'Pool Rate: ',
    text19: 'Step 1. Get UNI-V2 Liquidity tokens',
    text20: "UNI-V2 LP tokens are required. Once you've added liquidity to the",
    text21: 'pool you can stake your liquidity tokens on this page.',
    text22: 'Add',
    text23: 'liquidity',
    text24: 'Your liquidity deposits',
    text25: 'Your unclaimed UNI',
    text26: 'Claim',
    text27: ' When you withdraw, the contract will automagically claim UNI on your behalf!',
    text28: 'Deposit',
    text29: 'Deposit UNI-V2 LP Tokens',
    text30: 'Withdraw',
    text31: "UNI-V2 LP tokens available",
//pages/migratev1/
    text32: 'Migrate V1 Liquidity',
//components/positioncard/index
    text33: 'Your position',
    text34: 'Your pool share:',
    text35: "By adding liquidity youll earn 0.3% of all trades on this pair proportional to your share of the pool.Fees are added to the pool, accrue in real time and can be claimed by withdrawing your liquidity.",
    text36: 'Loading',
    text37: 'Manage',
    text38: 'Your total pool tokens:',
    text39: 'Pool tokens in rewards pool:',
    text40: 'Pooled',
    text41: 'View accrued fees and analytics',
    text42: 'Add',
    text43: 'Remove',
    text44: 'Manage Liquidity in Rewards Pool',
}