export default {
    text01: 'TRS price',
    text02: 'Current liquidity pledge',
    text03: 'Current mining output',
    text04: 'Current mining output value',
    text05: 'Total locked position',
    text06: 'My lock',
    text07: 'Unlocked quantity',
    text08: 'Wallet balance',
    text09: 'Lock-up period',
    text10: 'days',
    text11: 'extract',
    text12: 'Lock up',
    text13: 'Temporarily not opened',
    text14: 'Temporarily not opened',
}