export default {
    text01: 'TRS price',
    text02: 'Current liquidity pledge',
    text03: 'Dao total',
    text04: 'Dao Total value',
    text05: 'Total locked position',
    text06: 'My lock',
    text07: 'Unlocked quantity',
    text08: 'Wallet balance',
    text09: 'Lock-up period',
    text10: 'days',
    text11: 'extract',
    text12: 'Lock up',
    text13: 'Temporarily not opened',
    text14: 'Is about to open',
    text15: 'Unlock time',
    text16: 'My balance',
    text17: 'The unlocking time has not arrived yet',
    text18: 'The authorization...',
    text19: 'The lockup balance is zero',
    text20: 'Can receive',
}