export default {
    text04: 'Governance',
    text05: 'Repurchased',
    text06: 'Repurchase TTQ',
    text07: 'incentive',
    text08: 'Liquidity',
    text09: 'reward',
    text10: 'fee reward',
    text11: 'Audit institutions',
    text12: 'Exchange',
    text13: 'Liquidity',
    text14: 'TTQ price',
    text15: 'my balance',
    text16: ' price',
    text17: ' market value',
    text18: 'excavated quantity',
    text19: 'Current value',
    text20: 'Burn ',
    text21: 'S',
    text22: 'Total Lock',
    text23: 'Hot Pool',
    text24: 'more',
}