export default {
    text01: 'Current TVL',
    text02: 'TreeSwap: A new platform for the Huobi ecosystem',
    text03: 'A decentralized trading platform based on Huobi ecological chain to establish a trustless and highly decentralized financial infrastructure.',
    text04: 'Governance',
    text05: 'Repurchased',
    text06: 'Repurchase TRS',
    text07: 'incentive',
    text08: 'Liquidity',
    text09: 'reward',
    text10: 'fee reward',
    text11: 'Audit institutions',
    text12: 'Exchange',
    text13: 'Liquidity',
    text14: 'TRS price',
}