export default {
    text01: 'Liquidity provider rewards',
    text02: 'Liquidity providers earn a 0.3% fee on all trades proportional to their share of the pool. Fees are added to the pool, accrue in real time and can be claimed by withdrawing your liquidity.',
    text03: 'Read more about providing liquidity',
    text04: 'Your liquidity',
    text05: 'Create a pair',
    text06: 'Add Liquidity',
    text07: 'Connect to a wallet to view your liquidity.',
    text08: 'Loading',
    text09: 'Account analytics and accrued fees',
    text10: 'No liquidity found.',
    text11: 'Uniswap V1 liquidity found!',
    text12: "Don't see a pool you joined?",
    text13: "Migrate now.",
    text14: 'Import it.',
    text15: 'Use this tool to find pairs that dont automatically appear in the interface.',
    text16: 'Pool Found!',
    text17: 'Manage this pool.',
    text18: 'You don’t have liquidity in this pool yet.',
    text19: 'Add liquidity.',
    text20: 'No pool found.',
    text21: 'Invalid pair.',
    text22: 'Create pool.',
    text23: 'Loading',
    text24: 'Connect to a wallet to find pools',
    text25: 'Select a token to find your liquidity.',
}