export default {
    text01: 'Provision of liquidity',
    text02: 'pledge ',
    text03: ' No mining income is received',
    text04: 'My position',
    text05: ' Share than',
    text06: ' pledge',
    text07: 'Get working capital LP, need to mortgage to start liquidity mining',
    text08: 'pledged LP',
    text09: 'Get the benefits',
    text10: 'impower',
    text11: 'recaption liquidity',
    text12: '- working fund',
    text13: ' earn TRS',
    text14: 'get back',
    text15: 'Available Balance',
    text16: 'sign',
    text17: 'MAX',
    text18: 'cancel',
    text19: 'confirm',
}