export default {
    text01: 'Provision of liquidity',
    text02: 'staking ',
    text03: ' Unclaimed earnings',
    text04: 'My share',
    text05: ' Share than',
    text06: ' Stake',
    text07: 'Get working capital LP, need to mortgage to start liquidity mining',
    text08: 'Stake LP',
    text09: 'Get the benefits',
    text10: 'Approve',
    text11: 'recaption liquidity',
    text12: '- working fund',
    text13: ' earn TRS',
    text14: 'get back',
    text15: 'Balance',
    text16: 'unstake',
    text17: 'MAX',
    text18: 'cancel',
    text19: 'confirm',
}