export default {
    text01: 'Are you sure?',
    text02: 'Expert mode turns off the confirm transaction prompt and allows high slippage trades that often result in bad rates and lost funds.',
    text03: 'ONLY USE THIS MODE IF YOU KNOW WHAT YOU ARE DOING.',
    text04: 'Turn On Expert Mode',
    text05: 'Transaction Settings',
    text06: 'Interface Settings',
    text07: 'Toggle Expert Mode',
    text08: 'Bypasses confirmation modals and allows high slippage trades. Use at your own risk.',
    text09: 'Disable Multihops',
    text10: 'Restricts swaps to direct pairs only.',
    text11: 'Slippage tolerance',
    text12: 'Your transaction will revert if the price changes unfavorably by more than this percentage.',
    text13: 'Enter a valid slippage percentage',
    text14: 'Your transaction may fail',
    text15: "Your transaction may be frontrun",
    text16: 'Transaction deadline',
    text17: 'Your transaction will revert if it is pending for more than this long.',
    text18: 'minutes',
    text19: 'On',
    text20: 'Off',
}