export default {
    text01: 'From',
    text02: 'From (estimated)',
    text03: '+ Add a send (optional)',
    text04: 'To (estimated)',
    text05: 'To',
    text06: '— Remove send',
    text07: 'Price',
    text08: 'Slippage Tolerance',
    text09: 'Unsupported Asset',
    text10: 'Connect Wallet',
    text11: 'Insufficient liquidity for this trade.',
    text12: 'Try enabling multi-hop trades.',
    text13: 'Approving',
    text14: 'Approve',
    text15: "Price Impact High",
    text16: 'Price Impact Too High',
    text17: 'TTQSwap supports multi-currency conversion',
    text18: 'Trade fast, low slip point',
    text19: 'On',
    text20: 'Off',
    text21: 'Swap',
    text22: 'Capital pool',
    text23: 'Chain Bridge',
 }