export default {
    text01: '跨链桥',
    text02: '请选择跨链资产',
    text03: '从',
    text04: '到',
    text05: '收款地址',
    text06: '目标链接收款地址',
    text07: '请输入正确的erc20收款地址，地址错误将导致无法到账',
    text08: '不可填入合约地址或交易所充值地址',
    text09: '跨链数量',
    text10: '最大',
    text11: '余额：',
    text12: '暂未开放',
    text13: '查看记录',
    text14: '单笔最小限额 1 TTQ',
    text15: '打造聚合DEX、IMO、DAO的一站式DeFi生态平台',
    text16: 'TTQSWAP.COM',
}