export default {
    text01: '跨链桥',
    text02: '请选择跨链资产',
    text03: '从',
    text04: '到',
    text05: '收款地址',
    text06: '目标链接收款地址',
    text07: '请输入正确的erc20收款地址，地址错误将导致无法到账',
    text08: '不可填入合约地址或交易所充值地址',
    text09: '跨链数量',
    text10: '最大',
    text11: '余额：',
    text12: '暂未开放',
    text13: '查看记录',
    text14: '单笔最小限额 1 TTQ',
    text15: 'Ethereum生态币种交易 多快好省就选TTQSWAP.COM',
    text16: '打造DeFi生态最大的集DEX、IMO。DAO为一体的平台',
}