export default {
    //钱包
    text01: '连接到',
    text02: '显示名字',
    text03: '我的钱包',
    text04: '断开',
    text05: '切换',
    text06: '复制地址',
    text07: '前往 HECO',
    text08: '最近的交易',
    text09: '全部清除',
    text10: '您的交易将出现在这里……',
// pages/earn/index
    text11: 'TreeSwap 流动性矿业',
    text12: '存入您的流动性提供商令牌以接收TreeSwap协议治理令牌TRS。',
    text13: '查询更多TRS',
    text14: '参与池',
    text15: '没有活跃的池',
//pages/earn/manage
    text16: '流动性挖矿',
    text17: '总存款',
    text18: '池率: ',
    text19: '步骤1 获得TRS流动性代币',
    text20: "TRS LP令牌是必需的。 一旦你增加了流动性",
    text21: '你可以在这个页面上押注你的流动性代币。',
    text22: '添加',
    text23: '流动性',
    text24: '你的存款的流动性',
    text25: '你未领取的 TRS',
    text26: '索赔',
    text27: '当您撤回合同时，合同将自动代表您向TRS索赔!',
    text28: '存款',
    text29: '存入TRS代币',
    text30: '撤回',
    text31: 'TRS通证可用',
//pages/migratev1/
    text32: '迁移流动性',
//components/positioncard/index
    text33: '你的位置',
    text34: '你的交易池股份',
    text35: '通过增加流动性，你可以从这对交易中获得0.3%的收益，这与你在池中的份额成比例。费用被添加到池中，实时累积，并可以通过提取你的流动性来获取。',
    text36: '加载中',
    text37: '管理',
    text38: '你的交易池总通证:',
    text39: '奖励池中的代币:',
    text40: '池子的:',
    text41: '查看应计费用和分析:',
    text42: '添加',
    text43: '移除',
    text44: '管理奖励池的流动性',
//swap/AdvancedSwapDetails
    text45: '最少接收',
    text46: '最大接收',
    text47: '价格影响',
    text48: '手续费',
//pages/removeliquidity/index
    text49: '移除资金池代币会将你的头寸按当前比率转换回基础代币，与你在资金池中的份额成比例。应计费用包含在您收到的金额中。',
    text50: '数量',
    text51: '简单',
    text52: '详细',
    // text53: '获得 WETH',
    // text54: '获得 ETH',
    text55: '价格',
    text56: '同意',
    text57: '同意',
    text58: '同意',
    text59: '连接钱包',
    text60: '你将会收到',
    text61: '输出估计。如果价格变化超过 ',
    text62: '% 您的交易将恢复',
    text63: '确认',
    text64: '请尝试刷新页面，重新连接钱包',
}