export default {
    //钱包
    text01: '连接到',
    text02: '显示名字',
    text03: '我的钱包',
    text04: '断开',
    text05: '切换',
    text06: '复制地址',
    text07: '前往 HECO',
    text08: '最近的交易',
    text09: '全部清除',
    text10: '您的交易将出现在这里……',
// pages/earn/index
    text11: 'TreeSwap 流动性矿业',
    text12: '存入您的流动性提供商令牌以接收TreeSwap协议治理令牌TRS。',
    text13: '查询更多TRS',
    text14: '参与池',
    text15: '没有活跃的池',
//pages/earn/manage
    text16: '流动性挖矿',
    text17: '总存款',
    text18: '池率: ',
    text19: '步骤1 获得TRS流动性代币',
    text20: "TRS LP令牌是必需的。 一旦你增加了流动性",
    text21: '你可以在这个页面上押注你的流动性代币。',
    text22: '添加',
    text23: '流动性',
    text24: '你的存款的流动性',
    text25: '你未领取的 TRS',
    text26: '索赔',
    text27: '当您撤回合同时，合同将自动代表您向TRS索赔!',
    text28: '存款',
    text29: '存入TRS代币',
    text30: '撤回',
    text31: 'TRS通证可用',
//pages/migratev1/
    text32: '迁移V1流动性',
}