export default {
    text01: 'TRS 价格',
    text02: '当前流动性质押',
    text03: 'Dao总锁仓量',
    text04: 'Dao锁仓总价值',
    text05: '总锁仓量',
    text06: '我的锁仓',
    text07: '解锁数量',
    text08: '钱包余额',
    text09: '锁仓期',
    text10: '天',
    text11: '提取',
    text12: '锁仓',
    text13: '暂未开放',
    text14: '即将开放',
    text15: '解锁时间',
    text16: '我的余额',
    text17: '暂未到解锁时间',
    text18: '授权中...',
    text19: '锁仓余额为0',
    text20: '可领取',
}