export default {
    text01: '当前流动性质押',
    text02: 'TreeSwap：火币生态链的全新去中心化交易平台',
    text03: '一个基于火币生态链的去中心化交易平台,建立一个无需信任及高度去中心化的金融基础设施',
    text04: '治理机制',
    text05: '回购',
    text06: '回购TRS销毁',
    text07: '激励',
    text08: '流动性挖矿',
    text09: '奖励',
    text10: '手续费奖励',
    text11: '审计机构',
    text12: '兑换',
    text13: '流动性挖矿',
    text14: 'TRS价格',
    text15: '我的余额',
    text16: '价格',
    text17: '市值',
    text18: '当前挖出数量',
    text19: '当前挖出价值',
    text20: '已回购',
    text21: '数量',
    text22: '锁仓总量',
    text23: '热门矿池',
    text24: '更多',
}