export default {
    text01: '兑换',
    text02: '流动性挖矿',
    text03: '资金池',
    text04: 'TreeSwap白皮书',
    text05: '微信ID',
    text06: 'GitHub',
    text07: '推特',
    text08: '电报',
    text09: '审计报告',
    text10: '复制成功',
    text11: '首页',
    text12: '兑换',
    text13: '矿池',
    text14: '行情',
    text15: '董事会',
}