export default {
    text01: '提供流动性',
    text02: '质押 ',
    text03: '未领取挖矿收益',
    text04: '我的仓位',
    text05: ' 份额占比',
    text06: ' 质押',
    text07: '获得流动资金LP，需质押后才开始流动性挖矿',
    text08: '已质押LP',
    text09: '领取收益',
    text10: '授权',
    text11: '取回流动性',
    text12: '- 流动资金',
    text13: ' 赚取TRS',
    text14: '返回',
    text15: '可用余额',
    text16: '解押',
    text17: '最大',
    text18: '取消',
    text19: '确认',
    text20: '未领取',
    text21: '收益',
    text22: '取出',
    text23: '存入',
    text24: '未质押',
}