export default {
    text01: '从',
    text02: '从（估计的）',
    text03: '添加一个发送(可选)',
    text04: '到（估计的）',
    text05: '到',
    text06: '删除发送',
    text07: '价格',
    text08: '滑点大小',
    text09: '不支持的资产',
    text10: '连接的钱包',
    text11: '这种交易的流动性不足',
    text12: '尝试启用多跳交易',
    text13: '批准',
    text14: '同意',
    text15: "价格变动",
    text16: '价格变动过高',
    text17: 'TTQSwap支持多币种兑换',
    text18: '交易快、低滑点',
    text19: '开',
    text20: '关',
    text21: '兑换',
    text22: '资金池',
    text23: '跨链桥',
}